kind: pipeline
name: default

steps:

  - name: prepare
    image: node:12-alpine
    commands:
      - yarn install
      - yarn build

  - name: build
    image: plugins/docker
    settings:
      repo: bitsbeats/hub
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
      branch:
        - master

